-- Run FIRST, before any core rebuild, in asia-southeast2.
-- Keep v3 and upstream refreshes paused/unchanged throughout this controlled run.
-- IF NOT EXISTS preserves this baseline on retries; never reuse for a later migration.
CREATE SCHEMA IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation` OPTIONS(location='asia-southeast2');
ASSERT (SELECT COUNT(*) = 30 FROM `spheres-lombok-barat.kohort_bumil_v3.INFORMATION_SCHEMA.VIEWS`
 WHERE table_name IN ('v_birth_source_delay_category_long', 'v_birth_source_export_observations', 'v_birth_source_performance_daily_long', 'v_birth_weight_observations', 'v_birth_weight_source_audit', 'v_delivery_event_master_validated', 'v_delivery_source_first_report_native', 'v_delivery_timing_analysis_v1', 'v_pregnancy_dating_accuracy_v3_3', 'v_pregnancy_delivery_source_overlap_v3_3', 'v_pregnancy_outcome_tracking_dashboard_v3_3', 'v_pregnancy_outcome_trend_monthly_v3_3', 'v_pregnancy_source_crosswalk_v3_3', 'v_simrs_birth_weight_normalized', 'v_birth_source_performance_wide', 'v_delivery_monitoring_integrated', 'v_pregnancy_monitoring_integrated', 'v_birth_capture_step_wedge_daily', 'v_birth_outcome_event_dashboard', 'v_birth_outcome_period_comparison', 'v_birth_reporting_timeliness', 'v_pregnancy_delivery_source_long', 'v_pregnancy_monitoring_by_source_scope', 'v_birth_capture_step_wedge_wide', 'v_birth_reporting_timeliness_dashboard', 'v_birth_reporting_timeliness_evidence', 'v_edd_usg_hpht_paired', 'v_ga_usg_hpht_paired', 'v_edd_usg_hpht_paired_distribution', 'v_ga_usg_hpht_paired_distribution')) AS 'Expected all 30 current v3 reporting views';
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_view_columns` AS
 SELECT table_name,column_name,ordinal_position,data_type,is_nullable
 FROM `spheres-lombok-barat.kohort_bumil_v3.INFORMATION_SCHEMA.COLUMNS` WHERE table_name IN ('v_birth_source_delay_category_long', 'v_birth_source_export_observations', 'v_birth_source_performance_daily_long', 'v_birth_weight_observations', 'v_birth_weight_source_audit', 'v_delivery_event_master_validated', 'v_delivery_source_first_report_native', 'v_delivery_timing_analysis_v1', 'v_pregnancy_dating_accuracy_v3_3', 'v_pregnancy_delivery_source_overlap_v3_3', 'v_pregnancy_outcome_tracking_dashboard_v3_3', 'v_pregnancy_outcome_trend_monthly_v3_3', 'v_pregnancy_source_crosswalk_v3_3', 'v_simrs_birth_weight_normalized', 'v_birth_source_performance_wide', 'v_delivery_monitoring_integrated', 'v_pregnancy_monitoring_integrated', 'v_birth_capture_step_wedge_daily', 'v_birth_outcome_event_dashboard', 'v_birth_outcome_period_comparison', 'v_birth_reporting_timeliness', 'v_pregnancy_delivery_source_long', 'v_pregnancy_monitoring_by_source_scope', 'v_birth_capture_step_wedge_wide', 'v_birth_reporting_timeliness_dashboard', 'v_birth_reporting_timeliness_evidence', 'v_edd_usg_hpht_paired', 'v_ga_usg_hpht_paired', 'v_edd_usg_hpht_paired_distribution', 'v_ga_usg_hpht_paired_distribution');
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_view_definitions` AS
 SELECT table_name,view_definition FROM `spheres-lombok-barat.kohort_bumil_v3.INFORMATION_SCHEMA.VIEWS`
 WHERE table_name IN ('v_birth_source_delay_category_long', 'v_birth_source_export_observations', 'v_birth_source_performance_daily_long', 'v_birth_weight_observations', 'v_birth_weight_source_audit', 'v_delivery_event_master_validated', 'v_delivery_source_first_report_native', 'v_delivery_timing_analysis_v1', 'v_pregnancy_dating_accuracy_v3_3', 'v_pregnancy_delivery_source_overlap_v3_3', 'v_pregnancy_outcome_tracking_dashboard_v3_3', 'v_pregnancy_outcome_trend_monthly_v3_3', 'v_pregnancy_source_crosswalk_v3_3', 'v_simrs_birth_weight_normalized', 'v_birth_source_performance_wide', 'v_delivery_monitoring_integrated', 'v_pregnancy_monitoring_integrated', 'v_birth_capture_step_wedge_daily', 'v_birth_outcome_event_dashboard', 'v_birth_outcome_period_comparison', 'v_birth_reporting_timeliness', 'v_pregnancy_delivery_source_long', 'v_pregnancy_monitoring_by_source_scope', 'v_birth_capture_step_wedge_wide', 'v_birth_reporting_timeliness_dashboard', 'v_birth_reporting_timeliness_evidence', 'v_edd_usg_hpht_paired', 'v_ga_usg_hpht_paired', 'v_edd_usg_hpht_paired_distribution', 'v_ga_usg_hpht_paired_distribution');
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_sigizi_pregnancy_episode_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_sigizi_pregnancy_episode_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_epus_pregnancy_episode_adapter_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_epus_pregnancy_episode_adapter_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_sigizi_episode_canonical_map_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_sigizi_episode_canonical_map_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_sigizi_pregnancy_episode_canonical_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_sigizi_pregnancy_episode_canonical_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_epus_episode_canonical_map_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_epus_episode_canonical_map_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_epus_pregnancy_episode_canonical_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_epus_pregnancy_episode_canonical_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_pregnancy_episode_spine_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_pregnancy_episode_spine_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_pregnancy_final_canonical_map_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_pregnancy_final_canonical_map_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_pregnancy_usg_dating_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_pregnancy_usg_dating_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_pregnancy_outcome_events_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_pregnancy_outcome_events_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_pregnancy_outcome_tracking_v3_3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_pregnancy_outcome_tracking_v3_3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_source_records` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_source_records`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_dedup_base` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_dedup_base`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_event_member_map` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_event_member_map`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_event_master_unlinked` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_event_master_unlinked`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_sigizi_direct_rescue_v3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_sigizi_direct_rescue_v3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_event_member_map_v3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_event_member_map_v3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_event_master_v3` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_event_master_v3`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_t_delivery_source_first_report_native` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.t_delivery_source_first_report_native`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_v_pregnancy_monitoring_integrated` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.v_pregnancy_monitoring_integrated`;
CREATE TABLE IF NOT EXISTS `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_v_delivery_monitoring_integrated` AS SELECT * FROM `spheres-lombok-barat.kohort_bumil_v3.v_delivery_monitoring_integrated`;
SELECT 'BASELINE_CAPTURED' AS status, COUNT(DISTINCT table_name) AS captured_view_schemas FROM `spheres-lombok-barat.kohort_bumil_v3_validation.independent_20260903_view_columns`;
